=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Facebook-v2.0/schemas/order-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "from" : {
      "type" : "number" ,
      "required" : false
    } ,
    "to" : {
      "type" : "number" ,
      "required" : false
    } ,
    "amount" : {
      "type" : "number" ,
      "required" : false
    } ,
    "status" : {
      "type" : "string" ,
      "required" : false
    } ,
    "application" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "canvas_name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "namespace" : {
          "type" : "string" ,
          "required" : false
        } ,
        "id" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "country" : {
      "type" : "string" ,
      "required" : false
    } ,
    "created_time" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updated_time" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Facebook-v2.0/examples/order-example.json
{
  "id" : "9006187786070" ,
  "from" : 221159 ,
  "to" : 221159 ,
  "amount" : 1 ,
  "status" : "settled" ,
  "application" : {
    "name" : "SampleApp" ,
    "canvas_name" : "fbdschultzcredits" ,
    "namespace" : "fbdschultzcredits" ,
    "id" : "128163550571392"
  } ,
  "country" : "US" ,
  "created_time" : "2011-11-16T19:39:52+0000" ,
  "updated_time" : "2011-11-16T19:39:55+0000"
}
