=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Facebook-v2.0/schemas/payment-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "user" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "id" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "application" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "namespace" : {
          "type" : "string" ,
          "required" : false
        } ,
        "id" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "actions" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "type" : {
              "type" : "string" ,
              "required" : false
            } ,
            "status" : {
              "type" : "string" ,
              "required" : false
            } ,
            "currency" : {
              "type" : "string" ,
              "required" : false
            } ,
            "amount" : {
              "type" : "string" ,
              "required" : false
            } ,
            "time_created" : {
              "type" : "string" ,
              "required" : false
            } ,
            "time_updated" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "refundable_amount" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "currency" : {
          "type" : "string" ,
          "required" : false
        } ,
        "amount" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "items" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "type" : {
              "type" : "string" ,
              "required" : false
            } ,
            "product" : {
              "type" : "string" ,
              "required" : false
            } ,
            "quantity" : {
              "type" : "number" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "country" : {
      "type" : "string" ,
      "required" : false
    } ,
    "request_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "created_time" : {
      "type" : "string" ,
      "required" : false
    } ,
    "payout_foreign_exchange_rate" : {
      "type" : "number" ,
      "required" : false
    } ,
    "disputes" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "user_comment" : {
              "type" : "string" ,
              "required" : false
            } ,
            "time_created" : {
              "type" : "string" ,
              "required" : false
            } ,
            "user_email" : {
              "type" : "string" ,
              "required" : false
            } ,
            "status" : {
              "type" : "string" ,
              "required" : false
            } ,
            "reason" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Facebook-v2.0/examples/payment-example.json
{
  "id" : "519180411528475" ,
  "user" : {
    "name" : "Marco Alvarez" ,
    "id" : "500535225"
  } ,
  "application" : {
    "name" : "Friend Smash!" ,
    "namespace" : "friendsmashsample" ,
    "id" : "241431489326925"
  } ,
  "actions" : [
    {
      "type" : "charge" ,
      "status" : "completed" ,
      "currency" : "EUR" ,
      "amount" : "0.80" ,
      "time_created" : "2014-02-12T00:49:38+0000" ,
      "time_updated" : "2014-02-12T00:49:38+0000"
    } , {
      "type" : "refund" ,
      "status" : "completed" ,
      "currency" : "EUR" ,
      "amount" : "0.80" ,
      "time_created" : "2014-02-12T02:33:30+0000" ,
      "time_updated" : "2014-02-12T02:33:30+0000"
    }
  ] ,
  "refundable_amount" : {
    "currency" : "EUR" ,
    "amount" : "0.00"
  } ,
  "items" : [
    {
      "type" : "IN_APP_PURCHASE" ,
      "product" : "http://www.friendsmash.com/og/coins.html" ,
      "quantity" : 10
    }
  ] ,
  "country" : "US" ,
  "request_id" : "ISgQj4vGrrnmhGyABL5IaRmeUAoYlL2BrMoMOnmbsFj7AxrNurHej3jeZZS3710k" ,
  "created_time" : "2014-02-12T00:49:38+0000" ,
  "payout_foreign_exchange_rate" : 1.343826 ,
  "disputes" : [
    {
      "user_comment" : "I didn't get my Friend Smash coin! Please help!" ,
      "time_created" : "2014-02-12T01:37:27+0000" ,
      "user_email" : "mail@domain.com" ,
      "status" : "resolved" ,
      "reason" : "refunded_in_cash"
    }
  ]
}
