=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Stripe-v1/schemas/balance-schema.json
{
  "type":"object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "id": "http://jsonschema.net",
  "required":false,
  "properties":{
    "available": {
      "type":"array",
      "id": "http://jsonschema.net/available",
      "required":false,
      "items":
        {
          "type":"object",
          "id": "http://jsonschema.net/available/0",
          "required":false,
          "properties":{
            "amount": {
              "type":"number",
              "id": "http://jsonschema.net/available/0/amount",
              "required":false
            },
            "currency": {
              "type":"string",
              "id": "http://jsonschema.net/available/0/currency",
              "required":false
            }
          }
        }
    },
    "livemode": {
      "type":"boolean",
      "id": "http://jsonschema.net/livemode",
      "required":false
    },
    "object": {
      "type":"string",
      "id": "http://jsonschema.net/object",
      "required":false
    },
    "pending": {
      "type":"array",
      "id": "http://jsonschema.net/pending",
      "required":false,
      "items":
        {
          "type":"object",
          "id": "http://jsonschema.net/pending/0",
          "required":false,
          "properties":{
            "amount": {
              "type":"number",
              "id": "http://jsonschema.net/pending/0/amount",
              "required":false
            },
            "currency": {
              "type":"string",
              "id": "http://jsonschema.net/pending/0/currency",
              "required":false
            }
          }
        }
    }
  }
}

=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Stripe-v1/examples/balance.json
{
  "pending": [
    {
      "amount": 0,
      "currency": "cad"
    },
    {
      "amount": 363361,
      "currency": "usd"
    }
  ],
  "available": [
    {
      "amount": -358,
      "currency": "cad"
    },
    {
      "amount": -124791940,
      "currency": "usd"
    }
  ],
  "livemode": false,
  "object": "balance"
}
