=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Stripe-v1/schemas/charges-schema.json
{
    "type":"object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "id": "http://jsonschema.net",
    "required":false,
    "properties":{
        "count": {
            "type":"number",
            "id": "http://jsonschema.net/count",
            "required":false
        },
        "data": {
            "type":"array",
            "id": "http://jsonschema.net/data",
            "required":false,
            "items":
                {
                    "type":"object",
                    "id": "http://jsonschema.net/data/0",
                    "required":false,
                    "properties":{
                        "amount_refunded": {
                            "type":"number",
                            "id": "http://jsonschema.net/data/0/amount_refunded",
                            "required":false
                        },
                        "amount": {
                            "type":"number",
                            "id": "http://jsonschema.net/data/0/amount",
                            "required":false
                        },
                        "balance_transaction": {
                            "type":"string",
                            "id": "http://jsonschema.net/data/0/balance_transaction",
                            "required":false
                        },
                        "captured": {
                            "type":"boolean",
                            "id": "http://jsonschema.net/data/0/captured",
                            "required":false
                        },
                        "card": {
                            "type":"object",
                            "id": "http://jsonschema.net/data/0/card",
                            "required":false,
                            "properties":{
                                "address_city": {
                                    "type":"null",
                                    "id": "http://jsonschema.net/data/0/card/address_city",
                                    "required":false
                                },
                                "address_country": {
                                    "type":"null",
                                    "id": "http://jsonschema.net/data/0/card/address_country",
                                    "required":false
                                },
                                "address_line1_check": {
                                    "type":"null",
                                    "id": "http://jsonschema.net/data/0/card/address_line1_check",
                                    "required":false
                                },
                                "address_line1": {
                                    "type":"null",
                                    "id": "http://jsonschema.net/data/0/card/address_line1",
                                    "required":false
                                },
                                "address_line2": {
                                    "type":"null",
                                    "id": "http://jsonschema.net/data/0/card/address_line2",
                                    "required":false
                                },
                                "address_state": {
                                    "type":"null",
                                    "id": "http://jsonschema.net/data/0/card/address_state",
                                    "required":false
                                },
                                "address_zip_check": {
                                    "type":"null",
                                    "id": "http://jsonschema.net/data/0/card/address_zip_check",
                                    "required":false
                                },
                                "address_zip": {
                                    "type":"null",
                                    "id": "http://jsonschema.net/data/0/card/address_zip",
                                    "required":false
                                },
                                "country": {
                                    "type":"string",
                                    "id": "http://jsonschema.net/data/0/card/country",
                                    "required":false
                                },
                                "customer": {
                                    "type":"null",
                                    "id": "http://jsonschema.net/data/0/card/customer",
                                    "required":false
                                },
                                "cvc_check": {
                                    "type":"null",
                                    "id": "http://jsonschema.net/data/0/card/cvc_check",
                                    "required":false
                                },
                                "exp_month": {
                                    "type":"number",
                                    "id": "http://jsonschema.net/data/0/card/exp_month",
                                    "required":false
                                },
                                "exp_year": {
                                    "type":"number",
                                    "id": "http://jsonschema.net/data/0/card/exp_year",
                                    "required":false
                                },
                                "fingerprint": {
                                    "type":"string",
                                    "id": "http://jsonschema.net/data/0/card/fingerprint",
                                    "required":false
                                },
                                "id": {
                                    "type":"string",
                                    "id": "http://jsonschema.net/data/0/card/id",
                                    "required":false
                                },
                                "last4": {
                                    "type":"string",
                                    "id": "http://jsonschema.net/data/0/card/last4",
                                    "required":false
                                },
                                "name": {
                                    "type":"null",
                                    "id": "http://jsonschema.net/data/0/card/name",
                                    "required":false
                                },
                                "object": {
                                    "type":"string",
                                    "id": "http://jsonschema.net/data/0/card/object",
                                    "required":false
                                },
                                "type": {
                                    "type":"string",
                                    "id": "http://jsonschema.net/data/0/card/type",
                                    "required":false
                                }
                            }
                        },
                        "created": {
                            "type":"number",
                            "id": "http://jsonschema.net/data/0/created",
                            "required":false
                        },
                        "currency": {
                            "type":"string",
                            "id": "http://jsonschema.net/data/0/currency",
                            "required":false
                        },
                        "customer": {
                            "type":"string",
                            "id": "http://jsonschema.net/data/0/customer",
                            "required":false
                        },
                        "description": {
                            "type":"string",
                            "id": "http://jsonschema.net/data/0/description",
                            "required":false
                        },
                        "dispute": {
                            "type":"null",
                            "id": "http://jsonschema.net/data/0/dispute",
                            "required":false
                        },
                        "failure_code": {
                            "type":"null",
                            "id": "http://jsonschema.net/data/0/failure_code",
                            "required":false
                        },
                        "failure_message": {
                            "type":"null",
                            "id": "http://jsonschema.net/data/0/failure_message",
                            "required":false
                        },
                        "id": {
                            "type":"string",
                            "id": "http://jsonschema.net/data/0/id",
                            "required":false
                        },
                        "invoice": {
                            "type":"null",
                            "id": "http://jsonschema.net/data/0/invoice",
                            "required":false
                        },
                        "livemode": {
                            "type":"boolean",
                            "id": "http://jsonschema.net/data/0/livemode",
                            "required":false
                        },
                        "object": {
                            "type":"string",
                            "id": "http://jsonschema.net/data/0/object",
                            "required":false
                        },
                        "paid": {
                            "type":"boolean",
                            "id": "http://jsonschema.net/data/0/paid",
                            "required":false
                        },
                        "refunded": {
                            "type":"boolean",
                            "id": "http://jsonschema.net/data/0/refunded",
                            "required":false
                        },
                        "refunds": {
                            "type":"array",
                            "id": "http://jsonschema.net/data/0/refunds",
                            "required":false,
                            "items":
                                {
                                    "type":"object",
                                    "id": "http://jsonschema.net/data/0/refunds/0",
                                    "required":false,
                                    "properties":{
                                        "amount": {
                                            "type":"number",
                                            "id": "http://jsonschema.net/data/0/refunds/0/amount",
                                            "required":false
                                        },
                                        "balance_transaction": {
                                            "type":"string",
                                            "id": "http://jsonschema.net/data/0/refunds/0/balance_transaction",
                                            "required":false
                                        },
                                        "created": {
                                            "type":"number",
                                            "id": "http://jsonschema.net/data/0/refunds/0/created",
                                            "required":false
                                        },
                                        "currency": {
                                            "type":"string",
                                            "id": "http://jsonschema.net/data/0/refunds/0/currency",
                                            "required":false
                                        },
                                        "object": {
                                            "type":"string",
                                            "id": "http://jsonschema.net/data/0/refunds/0/object",
                                            "required":false
                                        }
                                    }
                                }
                            

                        }
                    }
                }
            

        },
        "object": {
            "type":"string",
            "id": "http://jsonschema.net/object",
            "required":false
        },
        "url": {
            "type":"string",
            "id": "http://jsonschema.net/url",
            "required":false
        }
    }
}

=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Stripe-v1/examples/invoices.json
{
  "object": "list",
  "url": "/v1/invoices",
  "count": 1,
  "data": [
    {
    "date": 1381134043,
    "id": "in_2hzEcE91Q3iHBb",
    "period_start": 1381134043,
    "period_end": 1381134043,
    "lines": {
      "data": [
        {
          "id": "su_2i0bDIlnaMV0Vq",
          "object": "line_item",
          "type": "subscription",
          "livemode": true,
          "amount": 100,
          "currency": "usd",
          "proration": false,
          "period": {
            "start": 1383817571,
            "end": 1386409571
          },
          "quantity": 1,
          "plan": {
            "interval": "month",
            "name": "Java Bindings Plan",
            "amount": 100,
            "currency": "usd",
            "id": "JAVA-PLAN-dbfd01a0-c28c-421d-8ae9-5a999575fa1b",
            "object": "plan",
            "livemode": false,
            "interval_count": 1,
            "trial_period_days": null
          },
          "description": null
        }
      ],
      "count": 1,
      "object": "list",
      "url": "/v1/invoices/in_2hzEcE91Q3iHBb/lines"
    },
    "subtotal": 0,
    "total": 0,
    "customer": "cus_2hzElrZhmfV9my",
    "object": "invoice",
    "attempted": true,
    "closed": true,
    "paid": true,
    "livemode": false,
    "attempt_count": 0,
    "amount_due": 0,
    "currency": "usd",
    "starting_balance": 0,
    "ending_balance": null,
    "next_payment_attempt": null,
    "charge": null,
    "discount": null,
    "application_fee": null
  }
  ]
}

=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Stripe-v1/examples/coupons.json
{
  "object": "list",
  "url": "/v1/coupons",
  "count": 1,
  "data": [
    {
    "id": "259FF",
    "percent_off": 25,
    "amount_off": null,
    "currency": "usd",
    "object": "coupon",
    "livemode": false,
    "duration": "repeating",
    "redeem_by": null,
    "max_redemptions": null,
    "times_redeemed": 0,
    "duration_in_months": 3
  }
  ]
}

=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Stripe-v1/examples/invoice_items.json
{
  "object": "list",
  "url": "/v1/invoiceitems",
  "count": 1,
  "data": [
    {
    "object": "invoiceitem",
    "id": "ii_2Xovytvup4IajJ",
    "date": 1378789336,
    "amount": 0,
    "livemode": false,
    "proration": true,
    "currency": "usd",
    "customer": "cus_2hzElrZhmfV9my",
    "description": "Remaining time on Prep Plan 2 after 10 Sep 2013",
    "invoice": null
  }
  ]
}

=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Stripe-v1/examples/events.json
{
  "object": "list",
  "url": "/v1/events",
  "count": 1,
  "data": [
    {
    "id": "evt_2i0bkMsBaZwLp1",
    "created": 1381139159,
    "livemode": false,
    "type": "charge.succeeded",
    "data": {
      "object": {
        "id": "ch_2i0bEetfZQnWS2",
        "object": "charge",
        "created": 1381139159,
        "livemode": false,
        "paid": true,
        "amount": 500,
        "currency": "usd",
        "refunded": false,
        "card": {
          "id": "card_2i0baJexR7HVae",
          "object": "card",
          "last4": "4242",
          "type": "Visa",
          "exp_month": 1,
          "exp_year": 2050,
          "fingerprint": "qhjxpr7DiCdFYTlH",
          "customer": null,
          "country": "US",
          "name": null,
          "address_line1": null,
          "address_line2": null,
          "address_city": null,
          "address_state": null,
          "address_zip": null,
          "address_country": null,
          "cvc_check": "pass",
          "address_line1_check": null,
          "address_zip_check": null
        },
        "captured": true,
        "refunds": [
  
        ],
        "balance_transaction": "txn_2i0bWLMtt8QnOF",
        "failure_message": null,
        "failure_code": null,
        "amount_refunded": 0,
        "customer": null,
        "invoice": null,
        "description": null,
        "dispute": null,
        "metadata": {
        }
      }
    },
    "object": "event",
    "pending_webhooks": 0,
    "request": "iar_2i0bwZ3Bh7TiPp"
  }
  ]
}

=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Stripe-v1/examples/transfers.json
{
  "object": "list",
  "url": "/v1/transfers",
  "count": 1,
  "data": [
    {
    "id": "tr_2OKKQ4A6HN1WJy",
    "object": "transfer",
    "date": 1376524800,
    "livemode": false,
    "amount": 286710,
    "currency": "usd",
    "status": "paid",
    "balance_transaction": "txn_2hrAStwRKjXiIp",
    "summary": {
      "charge_gross": 316670,
      "charge_fees": 29960,
      "charge_fee_details": [
        {
          "amount": 29960,
          "currency": "usd",
          "type": "stripe_fee",
          "description": null,
          "application": null
        }
      ],
      "refund_gross": 0,
      "refund_fees": 0,
      "refund_fee_details": [
  
      ],
      "adjustment_gross": 0,
      "adjustment_fees": 0,
      "adjustment_fee_details": [
  
      ],
      "validation_fees": 0,
      "validation_count": 0,
      "charge_count": 682,
      "refund_count": 0,
      "adjustment_count": 0,
      "net": 286710,
      "currency": "usd",
      "collected_fee_gross": 0,
      "collected_fee_count": 0,
      "collected_fee_refund_gross": 0,
      "collected_fee_refund_count": 0
    },
    "transactions": {
      "object": "list",
      "count": 682,
      "url": "/v1/transfers/tr_2OKKQ4A6HN1WJy/transactions",
      "data": [
        {
          "id": "ch_2Nn7UTSkz0cxq9",
          "type": "charge",
          "amount": 500,
          "currency": "usd",
          "net": 455,
          "created": 1376476192,
          "description": null,
          "fee": 45,
          "fee_details": [
            {
              "amount": 45,
              "currency": "usd",
              "type": "stripe_fee",
              "description": "Stripe processing fees",
              "application": null
            }
          ]
        },
        {
          "id": "ch_2Nn8hBMCCN0b1r",
          "type": "charge",
          "amount": 500,
          "currency": "usd",
          "net": 455,
          "created": 1376476252,
          "description": null,
          "fee": 45,
          "fee_details": [
            {
              "amount": 45,
              "currency": "usd",
              "type": "stripe_fee",
              "description": "Stripe processing fees",
              "application": null
            }
          ]
        },
        {
          "id": "ch_2Nn9rrWLlKk7Mj",
          "type": "charge",
          "amount": 500,
          "currency": "usd",
          "net": 455,
          "created": 1376476312,
          "description": null,
          "fee": 45,
          "fee_details": [
            {
              "amount": 45,
              "currency": "usd",
              "type": "stripe_fee",
              "description": "Stripe processing fees",
              "application": null
            }
          ]
        },
        {
          "id": "ch_2Nn9z9LTfcoJvW",
          "type": "charge",
          "amount": 100,
          "currency": "usd",
          "net": 67,
          "created": 1376476323,
          "description": null,
          "fee": 33,
          "fee_details": [
            {
              "amount": 33,
              "currency": "usd",
              "type": "stripe_fee",
              "description": "Stripe processing fees",
              "application": null
            }
          ]
        },
        {
          "id": "ch_2Nn9jymNURQqY5",
          "type": "charge",
          "amount": 100,
          "currency": "usd",
          "net": 67,
          "created": 1376476323,
          "description": null,
          "fee": 33,
          "fee_details": [
            {
              "amount": 33,
              "currency": "usd",
              "type": "stripe_fee",
              "description": "Stripe processing fees",
              "application": null
            }
          ]
        }
      ]
    },
    "other_transfers": [
      "tr_2OKKQ4A6HN1WJy"
    ],
    "account": null,
    "description": "STRIPE TRANSFER",
    "metadata": {
    },
    "statement_descriptor": null,
    "recipient": null
  }
  ]
}

=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Stripe-v1/examples/invoice-line_items.json
{
  "object": "list",
  "url": "/v1/invoices/in_2hzEcE91Q3iHBb/lines",
  "count": 1,
  "data": [
    {
    "id": "ii_2Xovytvup4IajJ",
    "object": "line_item",
    "type": "invoiceitem",
    "livemode": false,
    "amount": 1,
    "currency": "usd",
    "proration": true,
    "period": {
      "start": 1378789336,
      "end": 1378789336
    },
    "quantity": null,
    "plan": null,
    "description": "Remaining time on Prep Plan 2 after 10 Sep 2013"
  }
  ]
}
