=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Stripe-v1/schemas/recipients-schema.json
{
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "id": "http://jsonschema.net",
    "required": false,
    "properties": {
        "object": {
            "type": "string",
            "required": false
        },
        "url": {
            "type": "string",
            "required": false
        },
        "count": {
            "type": "number",
            "id": "http://jsonschema.net/count",
            "required": false
        },
        "data": {
            "type": "array",
            "id": "http://jsonschema.net/data",
            "required": false,
            "items": {
                "type": "object",
                "id": "http://jsonschema.net",
                "required": false,
                "properties": {
                    "active_account": {
                        "type": "object",
                        "id": "http://jsonschema.net/active_account",
                        "required": false,
                        "properties": {
                            "bank_name": {
                                "type": "string",
                                "id": "http://jsonschema.net/active_account/bank_name",
                                "required": false
                            },
                            "country": {
                                "type": "string",
                                "id": "http://jsonschema.net/active_account/country",
                                "required": false
                            },
                            "currency": {
                                "type": "string",
                                "id": "http://jsonschema.net/active_account/currency",
                                "required": false
                            },
                            "fingerprint": {
                                "type": "string",
                                "id": "http://jsonschema.net/active_account/fingerprint",
                                "required": false
                            },
                            "last4": {
                                "type": "string",
                                "id": "http://jsonschema.net/active_account/last4",
                                "required": false
                            },
                            "object": {
                                "type": "string",
                                "id": "http://jsonschema.net/active_account/object",
                                "required": false
                            },
                            "validated": {
                                "type": "boolean",
                                "id": "http://jsonschema.net/active_account/validated",
                                "required": false
                            }
                        }
                    },
                    "created": {
                        "type": "number",
                        "id": "http://jsonschema.net/created",
                        "required": false
                    },
                    "description": {
                        "type": "null",
                        "id": "http://jsonschema.net/description",
                        "required": false
                    },
                    "email": {
                        "type": "string",
                        "id": "http://jsonschema.net/email",
                        "required": false
                    },
                    "id": {
                        "type": "string",
                        "id": "http://jsonschema.net/id",
                        "required": false
                    },
                    "livemode": {
                        "type": "boolean",
                        "id": "http://jsonschema.net/livemode",
                        "required": false
                    },
                    "metadata": {
                        "type": "object",
                        "id": "http://jsonschema.net/metadata",
                        "required": false
                    },
                    "name": {
                        "type": "string",
                        "id": "http://jsonschema.net/name",
                        "required": false
                    },
                    "object": {
                        "type": "string",
                        "id": "http://jsonschema.net/object",
                        "required": false
                    },
                    "type": {
                        "type": "string",
                        "id": "http://jsonschema.net/type",
                        "required": false
                    },
                    "verified": {
                        "type": "boolean",
                        "id": "http://jsonschema.net/verified",
                        "required": false
                    }
                }
            }
        }
    }
}

=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Stripe-v1/examples/charges.json
{ 
"object": "list", 
"url": "/v1/charges", 
"count": 2, 
"data": [ 
  { 
  "id": "ch_2W2skeSVoEIgH8", 
  "object": "charge", 
  "created": 1378379935, 
  "livemode": false, 
  "paid": true, 
  "amount": 400, 
  "currency": "usd", 
  "refunded": false, 
  "card": 
    {
     "id": "cc_1SvbSeGL19eaMi", 
     "object": "card", 
     "last4": "4242", 
     "type": "Visa", 
     "exp_month": 8, 
     "exp_year": 2014, 
     "fingerprint": "qhjxpr7DiCdFYTlH", 
     "customer": null, 
     "country": "US", 
     "name": null, 
     "address_line1": null, 
     "address_line2": null, 
     "address_city": null, 
     "address_state": null, 
     "address_zip": null, 
     "address_country": null, 
     "cvc_check": null, 
     "address_line1_check": null, 
     "address_zip_check": null }, 
   "captured": true, "refunds": [ 
     { 
     "amount": 400, 
     "currency": "usd", 
     "created": 1378379955, 
     "object": "refund", 
     "balance_transaction": "txn_2W2s5pXW1h3t3Q" } ],
   "balance_transaction": "txn_2VrwM1WyxXifsV", 
   "failure_message": null, 
   "failure_code": null, 
   "amount_refunded": 400, 
   "customer": null, 
   "invoice": null, 
   "description": "Charge for test@example.com", 
   "dispute": null }, 
  { 
  "id": "ch_2W2skeusdf67IgH8", 
  "object": "charge", 
  "created": 1378374535, 
  "livemode": false, 
  "paid": true, 
  "amount": 500, 
  "currency": "usd", 
  "refunded": false, 
  "card": 
    {
     "id": "cc_1SvbSeGL19eaMi", 
     "object": "card", 
     "last4": "4242", 
     "type": "Visa", 
     "exp_month": 8, 
     "exp_year": 2014, 
     "fingerprint": "qhjxpr7DiCdFYTlH", 
     "customer": null, 
     "country": "US", 
     "name": null, 
     "address_line1": null, 
     "address_line2": null, 
     "address_city": null, 
     "address_state": null, 
     "address_zip": null, 
     "address_country": null, 
     "cvc_check": null, 
     "address_line1_check": null, 
     "address_zip_check": null }, 
   "captured": true, "refunds": [ 
     { 
     "amount": 500, 
     "currency": "usd", 
     "created": 1378379955, 
     "object": "refund", 
     "balance_transaction": "txn_2W2s5pXsdfsd3t3Q" } ],
   "balance_transaction": "txn_2W2s5pXsdfsd3t3Q", 
   "failure_message": null, 
   "failure_code": null, 
   "amount_refunded": 500, 
   "customer": null, 
   "invoice": null, 
   "description": "Charge 2 for test@example.com", 
   "dispute": null }
 ] }

=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Stripe-v1/examples/customers.json
{
    "object": "list", 
    "url": "v1/customers", 
    "count": 2, 
    "data": [
        {
            "object": "customer", 
            "created": 1378379137, 
            "id": "cus_2W2fj6IHUNOc2d", 
            "livemode": false, 
            "description": null, 
            "email": "victor@huge-success.net", 
            "delinquent": false, 
            "subscription": {
                "id": "su_2W2fay9kQDcftp", 
                "plan": {
                    "interval": "month", 
                    "name": "Basic", 
                    "amount": 1000, 
                    "currency": "usd", 
                    "id": "basic", 
                    "object": "plan", 
                    "livemode": false, 
                    "interval_count": 1, 
                    "trial_period_days": null
                }, 
                "object": "subscription", 
                "start": 1378379138, 
                "status": "active", 
                "customer": "cus_2W2fj6IHUNOc2d", 
                "cancel_at_period_end": false, 
                "current_period_start": 1378379138, 
                "current_period_end": 1380971138, 
                "ended_at": null, 
                "trial_start": null, 
                "trial_end": null, 
                "canceled_at": null, 
                "quantity": 1
            }, 
            "discount": null, 
            "account_balance": 0, 
            "cards": {
                "object": "list", 
                "count": 1, 
                "url": "/v1/customers/cus_2W2fj6IHUNOc2d/cards", 
                "data": [
                    {
                        "id": "card_2W2fhiuUB8W9Bq", 
                        "object": "card", 
                        "last4": "4242", 
                        "type": "Visa", 
                        "exp_month": 10, 
                        "exp_year": 2020, 
                        "fingerprint": "qhjxpr7DiCdFYTlH", 
                        "customer": "cus_2W2fj6IHUNOc2d", 
                        "country": "US", 
                        "name": null, 
                        "address_line1": null, 
                        "address_line2": null, 
                        "address_city": null, 
                        "address_state": null, 
                        "address_zip": null, 
                        "address_country": null, 
                        "cvc_check": null, 
                        "address_line1_check": null, 
                        "address_zip_check": null
                    }
                ]
            }, 
            "default_card": "card_2W2fhiuUB8W9Bq"
        }, 
        {
            "object": "customer", 
            "created": 1378379137, 
            "id": "cus_2W2fj6IHUNOc2d", 
            "livemode": false, 
            "description": null, 
            "email": "victor@huge-success.net", 
            "delinquent": false, 
            "subscription": {
                "id": "su_2W2fay9kQDcftp", 
                "plan": {
                    "interval": "month", 
                    "name": "Basic", 
                    "amount": 1000, 
                    "currency": "usd", 
                    "id": "basic", 
                    "object": "plan", 
                    "livemode": false, 
                    "interval_count": 1, 
                    "trial_period_days": null
                }, 
                "object": "subscription", 
                "start": 1378379138, 
                "status": "active", 
                "customer": "cus_2W2fj6IHUNOc2d", 
                "cancel_at_period_end": false, 
                "current_period_start": 1378379138, 
                "current_period_end": 1380971138, 
                "ended_at": null, 
                "trial_start": null, 
                "trial_end": null, 
                "canceled_at": null, 
                "quantity": 1
            }, 
            "discount": null, 
            "account_balance": 0, 
            "cards": {
                "object": "list", 
                "count": 1, 
                "url": "/v1/customers/cus_2W2fj6IHUNOc2d/cards", 
                "data": [
                    {
                        "id": "card_2W2fhiuUB8W9Bq", 
                        "object": "card", 
                        "last4": "4242", 
                        "type": "Visa", 
                        "exp_month": 10, 
                        "exp_year": 2020, 
                        "fingerprint": "qhjxpr7DiCdFYTlH", 
                        "customer": "cus_2W2fj6IHUNOc2d", 
                        "country": "US", 
                        "name": null, 
                        "address_line1": null, 
                        "address_line2": null, 
                        "address_city": null, 
                        "address_state": null, 
                        "address_zip": null, 
                        "address_country": null, 
                        "cvc_check": null, 
                        "address_line1_check": null, 
                        "address_zip_check": null
                    }
                ]
            }, 
            "default_card": "card_2W2fhiuUB8W9Bq"
        }
    ]
}
