=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Zendesk-v2/schemas/incrementalTicket-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "end_time" : {
      "type" : "number" ,
      "required" : false
    } ,
    "next_page" : {
      "type" : "string" ,
      "required" : false
    } ,
    "field_headers" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "group_name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "id" : {
          "type" : "string" ,
          "required" : false
        } ,
        "created_at" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "results" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "group_name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "id" : {
              "type" : "number" ,
              "required" : false
            } ,
            "created_at" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== moodislee/oas-raml-converter/test/data/apis-raml/raml/Zendesk-v2/examples/incrementalTicketExportResponse-example.json
{
  "end_time" : 1332034771 ,
  "next_page" : "https://domain.zendesk.com/api/v2/exports/tickets.json?start_time=1332034771" ,
  "field_headers" : {
    "group_name" : "Group" ,
    "id" : "Id" ,
    "created_at" : "Created at" 
  } ,
  "results" : [
    {
      "group_name" : "Support" ,
      "id" : 2 ,
      "created_at" : "2012-02-02T04:31:29Z" 
    } 
  ]
}
